config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about'

  resources :brands do
    resources :comments, only: [:destroy, :create, :index, :update]
    resource :favorites, only: [:destroy, :create, :index]
    collection do
      get 'search'
    end
  end

    get 'users/confirm' => 'users#confirm', as: 'users_confirm'
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  belongs_to :user
  validates :brand_name, presence: true
  validates :prefecture_id, presence: true
  validates :jan, length: { is: 13 },numericality: { only_integer: true }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  attachment :brand_image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  def self.search_for(content, method)
    if method == 'perfect'
      Brand.where(brand_name: content)
    elsif method == 'forward'
      Brand.where('brand_name LIKE ?', content + '%')
    elsif method == 'backward'
      Brand.where('brand_name LIKE ?', '%' + content)
    else
      Brand.where('brand_name LIKE ?', '%' + content + '%')
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :brand
  belongs_to :user
    validates :rate, numericality: {
        less_than_or_equal_to: 5,
        greater_than_or_equal_to: 1}, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :brand
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :brands
  has_many :favorites, dependent: :destroy
  validates :name, presence: true,length: { in: 2..15 }
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
   before_action :authenticate_user!,except: [:index]
   before_action :ensure_user, only: [:edit, :update, :destroy]
   before_action :set_q, only: [:index, :search]


  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    @brand.user_id = current_user.id
    if @brand.save
    redirect_to brands_path
    else
    render 'new'
    end
  end


  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    redirect_to brands_path
  end

  def index
    @brands = Brand.all.page(params[:page]).per(9)
  end

  def show
    @brand = Brand.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(params[:id])
    if @brand.comments.blank?
      @average_rate = 0
    else
      @average_rate = @brand.comments.average(:rate)
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    @brand.user_id = current_user.id
    if @brand.update(brand_params)
      redirect_to brands_path
    else
      render "edit"
    end
  end

  def search
    @results = @q.result
    @brands = Brand.all.page(params[:page]).per(9)
  end

  private
  def brand_params
    params.require(:brand).permit(:user_id, :prefecture_id, :brand_name, :jan , :body, :brand_image)
  end

  def ensure_user
    @brands = current_user.brands
    @brand = @brands.find_by(id: params[:id])
    redirect_to new_brand_path unless @brand
  end

  def set_q
    @q = Brand.ransack(params[:q])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
    @brand = Brand.find(params[:brand_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.brand_id = @brand.id
    @comment.score = Language.get_data(comment_params[:comment])
    @comment.save
  end

  def update
  end

  def destroy
    @brand = Brand.find(params[:brand_id])
    @comment = @brand.comments.find(params[:id])
    Comment.find_by(id: params[:id]).destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :rate)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
    @brand = Brand.find(params[:brand_id])
    favorite = current_user.favorites.new(brand_id: @brand.id)
    favorite.save
  end

  def destroy
    @brand = Brand.find(params[:brand_id])
    favorite = current_user.favorites.find_by(brand_id: @brand.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
# class SearchesController < ApplicationController
# 	def search
# 			@model = params[:model]
# 			@content = params[:content]
# 			@method = params[:method]
# 			if @model == 'brand'
# 				@records = Brand.search_for(@content, @method)
# 			end
# 			@brands = Brand.all.page(params[:page]).per(9)
# 	end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def confirm
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_index.html.erb
<!--銘柄一覧のページ・カード表示-->
<div class="row">
  <div class="flex">
    <% brands.each do |brand| %>
        <div class="item">
          <div class="card">
            <!--カード上部-->
              <div class="card-img-top-ground">
                <div class="card-img-top">
                  <%= link_to brand_path(brand) do %><%= attachment_image_tag brand, :brand_image, size: '100%', fallback:asset_path("no_image.jpg"),class:"card-img-top" %><% end %>
                </div>
              </div>
            <!--カード本文-->
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to brand.brand_name , brand_path(brand) , class:"text-dark"  %></br>
                    <i class="fas fa-map-pin"></i> <%= Prefecture.find_by(id: brand.prefecture_id).name %>
                </h5>
                <p class="card-text">JAN：<%= brand.jan %></p>
                <p class="card-text"><i class="fas fa-comment"></i> コメント <%= brand.comments.count %>件</p>
                <p class="card-text baloon-top"><i class="fas fa-lightbulb"></i> picked up comment! </br>
                  <% if brand.comments.blank? %>
                    まだコメントがありません
                  <% else %>
                    <!--18文字以上は省略-->
                    <% @score = brand.comments.maximum(:score) %>
                    <%= brand.comments.find_by(score:@score).comment.truncate(18) %>
                  <% end %></p>
                <p class="card-text"><i class="fas fa-heart"></i> いいね　<%= brand.favorites.count %></p>
              </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<%= paginate @brands %>

app/views/brands/edit.html.erb
<div class="container">
  <div class="col">
    <div class="row">
    <div class="col">
     <h3>銘柄編集</h3>
     <% if @brand.errors.any? %>
            <%= @brand.errors.count %>件のエラーが発生しました
            <% @brand.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>

      <div class="col">
        <%= form_with model:@brand, url:brand_path, method: :patch, local:true do |f| %>
        <table class="new-form-table">
          <tbody>
            <tr>
              <th><%= f.label :brand_image %></th>
              <td><%= f.attachment_field :brand_image , class: "form-control"%></td>
            </tr>

            <tr>
              <th><%= f.label :prefecture_id %></th>
              <td><%= f.collection_select :prefecture_id, Prefecture.all , :id, :name , { include_blank: "--選択してください--",:required => true}, {class: "form-control"} %></td>
            </tr>

            <tr>
              <th><%= f.label :brand_name %><i class="fas fa-question-circle my-tooltip" title="（例）あきたこまち"></i></th>
              <td><%= f.text_field :brand_name, class: "form-control" %></td>
            </tr>

            <tr>
              <th><%= f.label :jan %>（13桁）<i class="fas fa-question-circle my-tooltip" title="商品のバーコード下部に記載されている数字です"></i></th>
              <td><%= f.text_field :jan, class: "form-control" %></td>
            </tr>

            <tr>
              <th><%= f.label :body %></th>
              <td><%= f.text_area :body, class: "form-control" %></td>
            </tr>
          </tbody>
        </table>
        <div>
        <%= f.submit "編集保存" ,class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!--ツールチップ-->
<script>
  $(".my-tooltip").tooltip();
</script>

app/views/brands/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h3>銘柄一覧</h3>
            <%= link_to "銘柄新規投稿" , new_brand_path , class: "btn btn-warning" %>
        </div>
    </div>
    <%= render 'layouts/search'%>
    <%= render 'brands/index',brands: @brands %>
</div>

app/views/brands/new.html.erb
<div class="container">
  <div class="col">
    <div class="row">
      <div class="col">
        <h3>銘柄登録</h3>
          <% if @brand.errors.any? %>
            <%= @brand.errors.count %>件のエラーが発生しました
            <% @brand.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>
          <div class="col">
            <%= form_with model:@brand, url:brands_path, method: :post, local:true do |f| %>
            <table class="new-form-table">
              <tbody>
                <tr>
                  <th><%= f.label :brand_image %></th>
                  <td><%= f.attachment_field :brand_image, class: "form-control" %></td>
                </tr>

                <tr>
                  <th><%= f.label :prefecture_id %></th>
                  <td><%= f.collection_select :prefecture_id, Prefecture.all , :id, :name ,{ include_blank: "--選択してください--",:required => true}, {class: "form-control"} %></td>
                </tr>

                <tr>
                  <th><%= f.label :brand_name %><i class="fas fa-question-circle my-tooltip" title="（例）あきたこまち"></i></th>
                  <td><%= f.text_field :brand_name, class: "form-control",:required => true %></td>
                </tr>

                <tr>
                  <th><%= f.label :jan %>（13桁）<i class="fas fa-question-circle my-tooltip" title="商品のバーコード下部に記載されている数字です"></i></th>
                  <td><%= f.text_field :jan, class: "form-control",:required => true %></td>
                </tr>

                <tr>
                  <th><%= f.label :body %></th>
                  <td><%= f.text_area :body, class: "form-control" %></td>
                </tr>
              </tbody>
            </table>
            <div>
              <%= f.submit "新規登録" ,class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!--ツールチップ-->
<script>
  $(".my-tooltip").tooltip();
</script>

app/views/brands/search.html.erb
<%= render 'brands/index',brands: @results %>

app/views/brands/show.html.erb
<div class="container">
  <h3><span class="span"><%= Prefecture.find_by(id: @brand.prefecture_id).name %>産<%= @brand.brand_name %>
    <% if @brand.user_id == current_user.id %>
      <%= link_to "編集" , edit_brand_path(@brand.id) , class: "btn btn-success inline-btn" %>
      <%= link_to "削除" , brand_path(@brand.id) ,method: :delete, class: "btn btn-danger inline-btn" %></span>
    <% end %>
  </h3>
    <!--上部-->
    <div class="row">
      <div class="col-lg-3 col-md-5 offset-md-1 col-sm-5">
        <div class="img-top-ground"><%= attachment_image_tag @brand, :brand_image, size: '300x300',fallback: asset_path("no_image.jpeg"), class:"brand-image" %></div>
      </div>
      <div class ="col-lg-8 col-md-6 col-sm-6">
        <table class="table">
          <tbody>
            <tr>
              <th nowrap>産地名</th>
              <td><%= Prefecture.find_by(id: @brand.prefecture_id).name %></td>
            </tr>

            <tr>
              <th nowrap>銘柄名</th>
              <td><%= @brand.brand_name %></td>
            </tr>

            <tr>
              <th nowrap>JANコード</th>
              <td><%= @brand.jan %></td>
            </tr>

            <tr>
              <th nowrap>銘柄説明</th>
              <td><%= @brand.body %></td>
            </tr>

            <tr>
              <th nowrap>評価</th>
              <td class="average-review-rating" data-score=<%= @average_rate %>></td>
            </tr>
          </tbody>
        </table>
        <div id="brand_<%= @brand.id %>">
          <p class= "favorite-btn"><%= render "favorites/favorite-btn", brand: @brand %></p>
          <i class="fas fa-comments"></i><a class= "comments-count">コメント数：<%= @brand.comments.count %></a>
        </div>
      </div>
    </div>
    <!--コメント投稿欄-->
    <div class="row">
      <div class="col-lg-11 col-sm-11 offset-md-1">
        <%= form_with model:[@brand, @comment], remote: true do |f| %>
          <%= f.text_area :comment, rows:'5', placeholder: "何かコメントをしてみよう",class: "form-control col-12"%>
          <div id="rating-form">
            <%= f.label :rate%>
            <%= f.hidden_field :rate, :value => 'score' %>
            <span class="inline-btn">
            <%= f.submit "送信する",class:"btn btn-warning" %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
    <!--コメント一覧-->
    <div class="row-11 offset-md-1 comments"><%= render 'comments/index', brand: @brand %></div>
</div>

<!--評価の平均-->
<script>
  $('.average-review-rating').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
      score: function() {
        return $(this).attr('data-score')
      }
  });
</script>

<!--評価送信-->
<script>
  $('#rating-form').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    scoreName: 'comment[rate]'
  });
</script>

<!--comment/_index　評価結果-->
<script>
    $('.review-rating').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
        score: function() {
        return $(this).attr('data-score');
        }
    });
</script>

app/views/comments/_index.html.erb
<!--コメントの一覧-->
<% brand.comments.each do |comment| %>
<div class="col comment-ground">
    <!-- rateを表示 -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-5"><%= link_to user_path(comment.user_id) do %><%= attachment_image_tag comment.user, :profile_image, size: '150x150',fallback: asset_path("no_image.jpeg"), size: '150x150',class: "profiele-img col-sm-12" %><% end %></div>
            <div class="col-lg-4 col-sm-7">
                <p><%= link_to comment.user.name,user_path(comment.user_id) %>さん</p>
                <p>投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %></p>
                <span class="review-rating" data-score="<%= comment.rate %>">評価：</span>
                    <% if comment.user == current_user %>
                       <span class="comments">
                          <%= link_to "削除", brand_comment_path(comment.brand, comment), method: :delete, remote: true,class: "btn btn-danger" %>
                        </span>
                    <% end %>
            </div>
            <div class="col-lg-5 col-sm-12 comment-area">
                <p><%= comment.comment %></p>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/comments/create.js.erb
$("#brand_<%= @brand.id %> .comments-count").html("コメント数: <%= @brand.comments.count %>");
$(".comments").html("<%= j(render 'comments/index', brand: @brand) %>");
<!--空に書き換え-->
$("#comment_comment").val("");


 $('.review-rating').raty({
     readOnly: true,
     starOn: "<%= asset_path('star-on.png') %>",
     starOff: "<%= asset_path('star-off.png') %>",
     starHalf: "<%= asset_path('star-half.png') %>",
     score: function() {
     return $(this).attr('data-score');
     }
    });

app/views/comments/destroy.js.erb
$("#brand_<%= @brand.id %> .comments-count").html("コメント数: <%= @brand.comments.count %>");
$(".comments").html("<%= j(render 'comments/index', brand: @brand) %>");
$("#comment_comment").val("");

$('.review-rating').raty({
     readOnly: true,
     starOn: "<%= asset_path('star-on.png') %>",
     starOff: "<%= asset_path('star-off.png') %>",
     starHalf: "<%= asset_path('star-half.png') %>",
     score: function() {
     return $(this).attr('data-score');
     }
    });

app/views/favorites/_favorite-btn.html.erb
<% if brand.favorited_by?(current_user) %>
  <%= link_to brand.favorites.count, brand_favorites_path(brand), method: :delete, remote: true, class: "fas fa-heart unlike-btn" %>
<% else %>
  <%= link_to brand.favorites.count, brand_favorites_path(brand), method: :post, remote: true, class: "far fa-heart like-btn"  %>
<% end %>

app/views/favorites/create.js.erb
$("#brand_<%= @brand.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', brand: @brand) %>");

app/views/favorites/destroy.js.erb
$("#brand_<%= @brand.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', brand: @brand) %>");

app/views/favorites/index.html.erb
<h1>Favorites#index</h1>
<p>Find me in app/views/favorites/index.html.erb</p>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= search_form_for @q, url: search_brands_path do |f| %>
    <%= f.label :brand_name_cont, 'ブランド名' %>
    <%= f.search_field :brand_name_cont, placeholder:"  検索ワード入力" %>
    <%= f.submit '検索' ,class:'btn btn-warning' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>URUKASU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cdf8be78e7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <!--ヘッダー-->
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class ="container">
            <%= link_to image_tag("URUKASU.png") , root_path , class:"navbar-brand" %>
          <div>
          <ul class ="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class = "nav-item">
              <%= link_to "TOP", root_path, class:'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to "銘柄一覧", brands_path, class:"nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "マイページ", user_path(current_user.id),class:'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'nav-link' %>
            </li>
          <% else %>
            <li class = "nav-item">
              <%= link_to "TOP", root_path, class:'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to "新規登録", new_user_registration_path,class:'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to "ログイン", new_user_session_path,class:'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to "銘柄一覧", brands_path,class:"nav-link" %>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

    <!--検索バー-->
    
    <%= yield %>
    <!--フッター-->
    <footer class="bg-light">
      <div class="container">
        <div class="row">
          <div class="m-4"><p class="text-center">URUKASU</p></div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/searches/search.html.erb
<div class="container">
    <div class="row">
        <div class="col">
          <% if @model == 'brand' %>
          	<h3>銘柄検索 "<%= @content %>"</h3>
            <%= render 'brands/index', brands: @records %>
            <% else %>
            <h3>産地検索 "<%= @content %>"</h3>
            <%= render 'brands/index', brands: @records %>
          <% end %>
        </div>
    </div>
</div>

app/views/users/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div>
        <h3>本当に退会しますか？</h3>
      </div>

      <div>
        <p>
        退会すると、会員登録情報等が失われ、<br/>
        コメント投稿ができなくなります。<br/>
        退会する場合は、「退会する」をクリックしてください。
        </p>
      </div>

      <div>
        <p><%= link_to "退会しない", user_path(@user) %></p>
        <p><%= link_to "退会する",  user_registration_path, method: :delete %></p>s
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row">
        <h3><%= @user.name %>さんのマイページ</h3>
        <div class="user row">
          <div class="col-lg-12 col-sm-7">
          <p><%= attachment_image_tag @user, :profile_image, size: '200x200',fallback: asset_path("no_image.jpeg") %></p>
          </div>
            <div class="col-lg-12 col-sm-5">
              <% if @user.id == current_user.id %>
               <p><i class="fas fa-user-edit"></i><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success " %></p>
               <p><i class="fas fa-sign-out-alt"></i><%= link_to "退会", users_confirm_path, class: "btn btn-danger" %></p>
               <p><i class="fas fa-comment-dots"></i><%= link_to "銘柄新規投稿" , new_brand_path , class: "btn btn-warning" %></p>
              <% end %>
            </div>
        </div>
      </div>
    </div>
<!--いいね一覧-->
    <div class="col-lg-8">
      <div class="row">
        <h3>いいね一覧</h3>
        <div class="container">
        <table class = "table table-striped">
            <thead>
              <th>画像</th>
              <th>銘柄名</th>
            </thead>

            <tbody>
              <% @user.favorites.each do |f| %>
              <tr>
                  <td><%= attachment_image_tag f.brand, :brand_image, size: '100x100',fallback: asset_path("no_image.jpeg"), size: '100x100'%></td>
                  <td><%= link_to brand_path(f.brand_id) do %>
                      <%= f.brand.prefecture.name %><%= f.brand.brand_name %><% end %></td>
              </tr>
              <% end %>
            </tbody>
        </table>
        </div>
      </div>
      <!--コメント済み一覧-->
      <div class="row">
        <h3>コメント済み一覧</h3>
        <div class="container">
        <table class = "table table-striped">
            <thead>
              <th nowrap>画像</th>
              <th nowrap>銘柄名</th>
              <th nowrap>コメント</th>
            </thead>

            <tbody>
              <% @user.comments.each do |c| %>
              <tr>
                  <td><%= attachment_image_tag c.brand, :brand_image, size: '100x100',fallback: asset_path("no_image.jpeg"), size: '100x100' %></td>
                  <td><%= link_to brand_path(c.brand_id) do %>
                      <%= c.brand.prefecture.name %><%= c.brand.brand_name %><% end %></td>
                  <td><%= c.comment %></td>
              </tr>
              <% end %>
            </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>